# Generated by Django 5.1.6 on 2025-02-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrequest",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
