# Generated by Django 5.1.6 on 2025-02-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0005_alter_notification_notification_type_bookreview_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookreview",
            name="rating",
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="review_text",
            field=models.TextField(),
        ),
    ]
