# Generated by Django 5.1.6 on 2025-02-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0006_remove_bookreview_rating_and_more"),
        ("Message_Chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="Message_Chat.message",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend Request"),
                    ("book_request", "Book Request"),
                    ("request_update", "Request Update"),
                    ("due_reminder", "Due Reminder"),
                    ("book_rating", "Book Rating"),
                    ("book_review", "Book Review"),
                    ("new_message", "New Message"),
                ],
                max_length=20,
            ),
        ),
    ]
